### ISSUE TITLE
"signature mismatch" when running docker container.

### ISSUE THREAD

**Issue by guillheu** [maticnetwork/avail#118]
### What did I do
I ran the docker container after adding `+x` permissions to `entrypoint.sh` in the dockerfile :
`docker build -t avail .`
`docker run --rm avail`

### What did I expect
I expected the node to start running and attempt to connect to the network.

### What happened instead
This error popped up during node startup
`Error: Service(Client(VersionInvalid("RuntimeConstruction(Other(\"signature mismatch for: env:ext_hosted_header_builder_build_version_1\"))")))`

I am not sure what this means.

**Comment by MiguelDD1** [comment]
Solved in https://github.com/maticnetwork/avail/pull/119 .
Please be sure you use `develop` branch and also check the updated `README.md`
